/**
 * Delivery: write `.faithful/<fn>/` (patch.diff, spec.md, <fn>.lean, <fn>.provenance.json, VERIFY.md) from the session.
 * The user's source file is NEVER modified: the patch is theirs to apply. Everything stated is read from the session state.
 */
import { createTwoFilesPatch } from 'diff';
import { hashText, stampFrom, tierFromAxioms, weakerOf, TIER_LABEL, provedSentence, formatCount, type Tier } from '@faithful/core';
import { buildEvidenceBlock } from '@faithful/engine';
import type { Claim, Provenance, SessionState } from '@faithful/session';
import { isDifferentialDetail, isProofDetail, isSmtDetail } from '@faithful/session';
import { findFunction } from './candidate.js';
import type { SessionRuntime } from './runtime.js';

export interface DeliveryFiles {
  dir: string;
  files: string[];
  evidence: string;
}

/** The function declaration of an optimized source (a candidate may carry type aliases the user's file already has). */
export function extractCandidateFunction(candidateSource: string, fn: string): string {
  const f = findFunction(candidateSource, fn);
  return (f?.text ?? candidateSource).trim();
}

export function makePatch(file: string, original: string, fn: string, optimized: string, provenancePath: string, tier: Tier): string {
  const span = findFunction(original, fn);
  if (!span) throw new Error(`could not find function ${fn} in ${file}`);
  const note = `// Optimized by Faithful (${TIER_LABEL[tier]}). Claims and re-check commands: ${provenancePath}\n`;
  const next = original.slice(0, span.start) + note + extractCandidateFunction(optimized, fn) + original.slice(span.end);
  return createTwoFilesPatch(`a/${file}`, `b/${file}`, original, next, '', '', { context: 3 });
}

function stripImports(s: string): string {
  return s.replace(/^import .*$/gm, '').trim();
}

/** One standalone Lean file: model(s), spec, theorems with their checked proofs, and `#print axioms` for each. */
export function renderLeanFile(s: SessionState, incumbentProof: { theorem: string; statement: string; helpers: string; proof: string; candidateModel?: string } | null): { text: string; theorems: string[] } {
  const t = s.translation && s.translation.ok ? s.translation.value : null;
  const ag = s.agreement;
  if (!t || !ag) throw new Error('nothing to render: no translation or agreement');
  const parts: string[] = ['import Faithful.Tactics', '', `-- Faithful: ${t.fnName}. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.`, `-- Agreement hash: ${ag.hash}`, '', stripImports(t.lean.source), ''];
  const theorems: string[] = [];
  const op = s.proofs.find((p) => p.theoremId === 'original_meets_spec');
  // candidate model first (its text may repeat the original's; incumbentProof.candidateModel is the combined text used when proving)
  if (incumbentProof?.candidateModel) {
    const origBody = stripImports(t.lean.source);
    const body = stripImports(incumbentProof.candidateModel);
    parts.push('-- candidate model', body.startsWith(origBody) ? body.slice(origBody.length).trim() : body, '');
  }
  parts.push('-- agreed spec', ag.specLean.trim(), '');
  if (op?.accepted) {
    const h = op.accepted.helpers.trim();
    if (h) parts.push(h, '');
    parts.push(`theorem ${op.theoremId} : ${op.statement} :=`, op.accepted.proof.trim().startsWith('by') ? op.accepted.proof.trim() : `  ${op.accepted.proof.trim()}`, '');
    theorems.push(op.theoremId);
  }
  if (incumbentProof) {
    const h = incumbentProof.helpers.trim();
    if (h) parts.push(h, '');
    parts.push(`theorem ${incumbentProof.theorem} : ${incumbentProof.statement} :=`, incumbentProof.proof.trim().startsWith('by') ? incumbentProof.proof.trim() : `  ${incumbentProof.proof.trim()}`, '');
    theorems.push(incumbentProof.theorem);
  }
  for (const th of theorems) parts.push(`#print axioms ${th}`);
  return { text: parts.join('\n') + '\n', theorems };
}

export function specMarkdown(s: SessionState): string {
  const ag = s.agreement!;
  const t = s.translation && s.translation.ok ? s.translation.value : null;
  const lines = [
    `# Spec: \`${s.fn}\``,
    '',
    `Agreed ${ag.at}. Agreement hash \`${ag.hash}\`. Everything proved is pinned to this hash.`,
    '',
    '## In words',
    '',
    ag.english,
    '',
    '## Lean',
    '',
    '```lean',
    ag.specLean.trim(),
    '```',
    '',
    '## Preconditions',
    '',
    ...ag.preconditions.map((p) => `- ${p.words}`),
    '',
  ];
  if (ag.carveOuts.length) {
    lines.push('## Carve-outs (known problems you chose to exclude)', '', ...ag.carveOuts.map((c) => `- **${c.words}**`), '');
  }
  if (ag.rulings.length) {
    lines.push('## Rulings', '', ...ag.rulings.map((r) => (r.ruling === 'spec-wrong' ? `- challenge ${r.challengeId}: the spec was wrong${r.note ? ` (${r.note})` : ''}` : `- challenge ${r.challengeId}: the function was wrong; ${r.then === 'carve-out' ? 'carved out' : 'to be fixed'}${r.note ? ` (${r.note})` : ''}`)), '');
  }
  if (t) lines.push('## Model', '', `The Lean model is produced by a fixed translator (docs/TRANSLATOR.md); model hash \`${t.lean.hash}\`.`, '');
  return lines.join('\n');
}

export function verifyMarkdown(fn: string, dir: string, leanDir: string | null): string {
  return [
    `# Re-checking ${fn}`,
    '',
    'Nothing here asks you to trust the tool. Each command re-runs a check.',
    '',
    '```',
    `faithful verify ${dir}`,
    '```',
    '',
    'This recomputes every hash in `provenance.json`, re-runs Lean on the proof file, re-runs the differential test and the bounded SMT check, and prints the evidence line again.',
    '',
    'To check the proofs with Lean alone:',
    '',
    '```',
    `cd ${leanDir ?? '<faithful>/lean'} && lake env lean ${dir}/${fn}.lean`,
    '```',
    '',
    'The output lists `#print axioms` for each theorem. A proof counts as Proved only if the axioms are within `propext`, `Classical.choice`, `Quot.sound`. A theorem that depends on `sorryAx` or any other axiom is not a proof. One that depends on a `native_decide` axiom is labeled "Proved (trusting the compiler)".',
    '',
    'To apply the optimized function: `git apply ' + `${dir}/patch.diff` + '` (Faithful never modifies your files).',
    '',
  ].join('\n');
}

export async function deliver(rt: SessionRuntime): Promise<DeliveryFiles> {
  const s = rt.state;
  const t = rt.translation;
  const ag = s.agreement;
  if (!t || !ag) throw new Error('nothing to deliver: no agreed spec');
  const fn = s.fn;
  const o = s.optimize;
  const inc = o.candidates.find((c) => c.id === o.incumbentId) ?? null;
  const stamp = stampFrom(s.toolchain ?? (await (await import('@faithful/core')).captureToolchain()));
  const claims: Claim[] = [];

  // original meets spec
  const op = s.proofs.find((p) => p.theoremId === 'original_meets_spec');
  let deliveredTier: Tier = 'not-proved';
  if (op?.accepted) {
    const tier = tierFromAxioms(op.accepted.axioms) ?? 'not-proved';
    claims.push({ kind: 'original-meets-spec', tier, statement: op.statementWords, theorem: op.theoremId, axioms: op.accepted.axioms, attempts: op.attempts.length, minutes: op.ms / 60_000 });
  } else if (op) {
    claims.push({ kind: 'original-meets-spec', tier: 'not-proved', statement: op.statementWords, theorem: op.theoremId, attempts: op.attempts.length, minutes: op.ms / 60_000 });
  }

  let incumbentProof: Parameters<typeof renderLeanFile>[1] = null;
  let optimizedSource = t.source.text;
  let evidenceProof: { tier: 'proved' | 'proved-trusting-compiler' } | undefined;
  let bounded: { k: number } | undefined;
  let differentialN: number | undefined;
  let mutation: { caught: number; total: number } | undefined;
  let speed: Parameters<typeof buildEvidenceBlock>[0]['speed'];

  if (inc) {
    optimizedSource = inc.source;
    const dd = inc.stages.find((x) => x.stage === 'differential')?.detail;
    const sd = inc.stages.find((x) => x.stage === 'smt')?.detail;
    const pd = inc.stages.find((x) => x.stage === 'proof')?.detail as Record<string, unknown> | undefined;
    let tier: Tier = 'tested';
    if (isDifferentialDetail(dd)) {
      claims.push({ kind: 'candidate-vs-original-differential', tier: 'tested', statement: 'The optimized function returns the same result as the original on generated inputs under the preconditions, and the same inputs catch the original\'s broken copies.', inputs: dd.compared, seed: dd.seed, mutation: dd.mutation ? { caught: dd.mutation.caught, total: dd.mutation.total, undistinguished: dd.mutation.undistinguished } : undefined });
      if (dd.mutation) mutation = { caught: dd.mutation.caught, total: dd.mutation.total };
    }
    if (isSmtDetail(sd) && sd.result === 'unsat') {
      tier = 'verified-to-k';
      bounded = { k: sd.k };
      claims.push({ kind: 'candidate-vs-original-smt', tier: 'verified-to-k', statement: `Z3 found no distinguishing input among all inputs up to size k=${sd.k} under the stated encoding (${sd.encoding}).`, k: sd.k, bounds: sd.bounds });
    }
    if (pd && isProofDetail(pd) && pd.accepted) {
      const ptier = tierFromAxioms(pd.axioms) ?? null;
      if (ptier) {
        tier = ptier;
        evidenceProof = { tier: ptier };
        const acc = pd.accepted as { helpers: string; proof: string };
        incumbentProof = { theorem: pd.theoremId, statement: String(pd.statement), helpers: acc.helpers, proof: acc.proof, candidateModel: String(pd.candidateModel ?? '') };
        claims.push({ kind: 'candidate-meets-spec', tier: ptier, statement: 'The optimized function (as modeled by the translator) meets the agreed spec under the preconditions, and stays inside the model\'s range.', theorem: pd.theoremId, axioms: pd.axioms, attempts: pd.attempts });
      }
    }
    deliveredTier = tier;
    if (inc.speedup) speed = { ratio: { estimate: inc.speedup.ratio, lo: inc.speedup.lo, hi: inc.speedup.hi }, verdict: inc.speedup.significant ? 'faster' : 'not-distinguished' };
    if (inc.outcome === 'accepted-at-verified') claims.push({ kind: 'candidate-vs-original-smt', tier: 'verified-to-k', statement: 'Accepted by the user at the Verified-to-k tier; not proved.', acceptedByUser: true });
  } else if (op?.accepted) {
    deliveredTier = tierFromAxioms(op.accepted.axioms) ?? 'not-proved';
    evidenceProof = deliveredTier === 'proved' || deliveredTier === 'proved-trusting-compiler' ? { tier: deliveredTier } : undefined;
  }

  // N for "checked against the TypeScript on N inputs": the delivered function's model check
  const need = inc ? 'candidate' : 'original';
  let mc = s.modelChecks.filter((m) => m.subject === need && (need === 'original' || m.candidateId === inc?.id)).at(-1);
  if (!mc && evidenceProof) {
    if (need === 'original') await rt.checkModel('original', t, null);
    mc = rt.state.modelChecks.filter((m) => m.subject === need).at(-1);
  }
  differentialN = mc?.inputs;
  const modelDisagrees = (mc?.disagreements ?? 0) > 0;
  if (modelDisagrees) {
    // The Lean model disagrees with the TypeScript on some input: a proof about the model says nothing about the function.
    evidenceProof = undefined;
    if (deliveredTier === 'proved' || deliveredTier === 'proved-trusting-compiler') deliveredTier = bounded ? 'verified-to-k' : 'tested';
  }
  const evidence = buildEvidenceBlock({
    stamp,
    proof: evidenceProof,
    bounded,
    differential: differentialN !== undefined ? { inputs: differentialN } : undefined,
    mutation,
    speed,
  } as never);

  const dir = `.faithful/${fn}`;
  const files: string[] = [];
  const write = async (rel: string, text: string) => {
    files.push(rel);
    await rt.store.writeText(fn, rel, text);
  };

  const prov: Provenance = {
    schema: 1,
    fn,
    file: s.file,
    generatedAt: new Date().toISOString(),
    stamp,
    deliveredTier,
    hashes: { originalSource: hashText(t.source.text), optimizedSource: hashText(optimizedSource), patch: '', leanFile: '', model: t.lean.hash, spec: ag.specHash, agreement: ag.hash },
    originalSource: t.source.text,
    originalFileSource: rt.fileText,
    optimizedSource,
    preconditions: ag.preconditions,
    carveOuts: ag.carveOuts,
    rulings: ag.rulings,
    claims,
    benchmark: o.baseline ? { baseline: o.baseline, incumbent: inc?.bench ?? null, speedup: inc?.speedup ?? null, distribution: o.baseline.distribution, sizes: o.baseline.sizes } : null,
    candidates: o.candidates.map((c) => ({ id: c.id, round: c.round, sourceHash: hashText(c.source), outcome: c.outcome, tier: c.tier, rejection: c.rejection, speedup: c.speedup })),
    codex: { calls: s.calls.length, failed: s.calls.filter((c) => c.error).length, model: stamp.modelId, effort: stamp.toolchain.codex.effort, version: stamp.toolchain.codex.version },
    caveats: [
      ...(ag.carveOuts.length ? [`This result excludes carved-out inputs: ${ag.carveOuts.map((c) => c.words).join(' ')}`] : []),
      ...(inc?.outcome === 'accepted-at-verified' ? ['The optimized function was accepted by the user at the Verified-to-k tier. It is NOT proved.'] : []),
      ...(deliveredTier === 'not-proved' ? ['Nothing is proved for the delivered function.'] : []),
      ...(modelDisagrees ? [`The Lean model disagreed with the TypeScript on ${mc!.disagreements} generated input(s), so no Proved claim is made even though a Lean proof about the model exists.`] : []),
      ...(evidenceProof ? [provedSentence(differentialN ?? 0)] : []),
    ],
  };

  const lean = (op?.accepted || incumbentProof) ? renderLeanFile(s, incumbentProof) : null;
  if (lean) {
    prov.hashes.leanFile = hashText(lean.text);
    await write(`${fn}.lean`, lean.text);
  }
  let patch = '';
  if (inc && s.file) {
    patch = makePatch(s.file, rt.fileText, fn, optimizedSource, `${dir}/${fn}.provenance.json`, deliveredTier);
  }
  prov.hashes.patch = hashText(patch);
  await write('patch.diff', patch || '# no optimized function was delivered (no incumbent)\n');
  await write('spec.md', specMarkdown(s));
  await write(`${fn}.provenance.json`, JSON.stringify(prov, null, 2) + '\n');
  await write('VERIFY.md', verifyMarkdown(fn, dir, null));
  await rt.emit({ kind: 'deliver.done', dir, files, at: new Date().toISOString() });
  void formatCount;
  void weakerOf;
  return { dir, files, evidence: evidence.text };
}
