import Faithful.Tactics

-- Faithful: clamp. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:93ba2aa14335f0966f2237b442ece33637a11383d472ad820dd8653a1781917a

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def clamp (value : Int) (lo : Int) (hi : Int) : Except String (Int) :=
  do
    if (lo > hi) then
      throw "clamp: lower bound exceeds upper bound"
    else
      pure (Min.min (Max.max value lo) hi)

def clamp_chk (value : Int) (lo : Int) (hi : Int) : Faithful.Chk (Int) :=
  do
    if (lo > hi) then
      throw (Faithful.Fail.thrown "clamp: lower bound exceeds upper bound")
    else
      pure (Min.min (Max.max value lo) hi)

def clamp_rangeOk (value : Int) (lo : Int) (hi : Int) : Bool := Faithful.rangeOkOf (Model.clamp_chk value lo hi)

def clamp_pre (value : Int) (lo : Int) (hi : Int) : Bool :=
  ((Faithful.intOk value) && (Faithful.intOk lo) && (Faithful.intOk hi)) && (Model.clamp_rangeOk value lo hi)

end Model

-- agreed spec
namespace Spec

def spec (value : Int) (lo : Int) (hi : Int) : Except String (Int) :=
  if lo > hi then
    .error "clamp: lower bound exceeds upper bound"
  else if value < lo then
    .ok lo
  else if value > hi then
    .ok hi
  else
    .ok value

end Spec

theorem original_meets_spec : ∀ (value : Int) (lo : Int) (hi : Int), Model.clamp_pre value lo hi = true → (match Model.clamp value lo hi with | .ok _ => true | .error _ => false) = true → Model.clamp value lo hi = Spec.spec value lo hi :=
by
  intro value lo hi _ _
  by_cases h : lo > hi
  · simp [Model.clamp, Spec.spec, h]
  · by_cases hv : value < lo
    · have hmax : Max.max value lo = lo := max_eq_right (le_of_lt hv)
      have hmin : Min.min lo hi = lo := min_eq_left (by omega)
      simp [Model.clamp, Spec.spec, h, hv, hmax, hmin]
    · by_cases hh : value > hi
      · have hlo : lo ≤ value := by omega
        have hmax : Max.max value lo = value := max_eq_left hlo
        have hmin : Min.min value hi = hi := min_eq_right (by omega)
        simp [Model.clamp, Spec.spec, h, hv, hh, hmax, hmin]
      · have hlo : lo ≤ value := by omega
        have hhi : value ≤ hi := by omega
        have hmax : Max.max value lo = value := max_eq_left hlo
        have hmin : Min.min value hi = value := min_eq_left hhi
        simp [Model.clamp, Spec.spec, h, hv, hh, hmax, hmin]

#print axioms original_meets_spec
