import Faithful.Tactics

-- Faithful: clamp. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:8a9c5b49c796624af153923c415d97c8fd4eaf8f258897006d7cbbd70bd6a120

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def clamp (value : Int) (lo : Int) (hi : Int) : Except String (Int) :=
  do
    if (lo > hi) then
      throw "clamp: lower bound exceeds upper bound"
    else
      pure (Min.min (Max.max value lo) hi)

def clamp_chk (value : Int) (lo : Int) (hi : Int) : Faithful.Chk (Int) :=
  do
    if (lo > hi) then
      throw (Faithful.Fail.thrown "clamp: lower bound exceeds upper bound")
    else
      pure (Min.min (Max.max value lo) hi)

def clamp_rangeOk (value : Int) (lo : Int) (hi : Int) : Bool := Faithful.rangeOkOf (Model.clamp_chk value lo hi)

def clamp_pre (value : Int) (lo : Int) (hi : Int) : Bool :=
  ((Faithful.intOk value) && (Faithful.intOk lo) && (Faithful.intOk hi)) && (Model.clamp_rangeOk value lo hi)

end Model

-- agreed spec
namespace Spec

def spec (value : Int) (lo : Int) (hi : Int) : Except String (Int) :=
  if lo > hi then
    .error "clamp: lower bound exceeds upper bound"
  else
    .ok (max lo (min value hi))

end Spec

theorem original_meets_spec : ∀ (value : Int) (lo : Int) (hi : Int), Model.clamp_pre value lo hi = true → (match Model.clamp value lo hi with | .ok _ => true | .error _ => false) = true → Model.clamp value lo hi = Spec.spec value lo hi :=
by
  intro value lo hi _ hrun
  by_cases h : lo > hi
  · simp [Model.clamp, h] at hrun
  · have hlo : lo ≤ hi := by omega
    simp [Model.clamp, Spec.spec, h]
    omega

#print axioms original_meets_spec
