/**
 * Sanity mode: the SMT encoding of the ORIGINAL, evaluated by Z3 on concrete inputs, must give exactly what the
 * range-instrumented TypeScript original gives in the sandbox (and, when a LeanEvaluator is injected, what the Lean
 * checked twin `#eval`s to). Any difference is an encoder bug.
 *
 * Per function: one encoding at capacities that fit every input (symbolic lengths, padding unconstrained), then per
 * input `(reset) <encoding> (assert input = constants) (check-sat) (get-value status+output)`. A second pass checks that the
 * model's output is the ONLY one the encoding allows for that input (`(assert (not (= output decoded)))` must be
 * unsat): an encoding whose output depended on padding slots would pass the first pass by luck and fail this one.
 *
 * Range-violation outcomes are compared by detail text (`<kind> check failed at line L: <text>`), which checks the
 * order of the checks, not just their presence. Inputs where the encoder reached its unrolling bound (`fuel`) or the
 * TypeScript side faulted (timeout) are counted and not compared.
 */
import { generateInputs, loadCorpus, outcomeEqual, type LeanEvaluator, type Sandbox } from '@faithful/engine';
import { leanChkEvalExpr, parseLeanOutcome, translateWithIr, type IrProgram, type Outcome, type Translation, type Ty, type Val } from '@faithful/translate';
import type { Z3Info } from '@faithful/core';
import { Encoder, type Shared } from './encode.js';
import { declareInput, type Bounds } from './inputs.js';
import { decodeOutcome, lookup, outcomeTerms, type EncodedOutcome } from './outcome.js';
import { runInstrumented } from './replay.js';
import { readAnswers, transcript } from './sexpr.js';
import { Smt, TooLarge, Unsupported, and, eq, int, not } from './terms.js';
import { eqConst, type SV } from './values.js';
import type { Z3Driver } from './z3.js';

export interface SanityOptions {
  /** Inputs per function (generated by the engine's `generateInputs`). Default 60. */
  n?: number;
  seed?: number;
  /** First unrolling bound tried; lowered when the encoding is too large. Default 24. */
  unroll?: number;
  /** Inputs per Z3 call. Default 30. */
  chunk?: number;
  /** Z3 wall-clock budget per call, ms. Default 120000. */
  solveMs?: number;
  /** Size budget of one encoding (characters of SMT-LIB). Default 8,000,000. */
  maxChars?: number;
  /** Input sizes for the generator. Default arrays 6, strings 8 (the default equivalence bounds). */
  maxArray?: number;
  maxString?: number;
  lean?: LeanEvaluator;
  sandbox?: Sandbox;
}

export interface SanityMismatch {
  input: Val[];
  against: 'ts' | 'lean' | 'uniqueness' | 'solver';
  expected: Outcome | string;
  encoder: EncodedOutcome | string;
}

export interface SanityReport {
  fnName: string;
  encodable: boolean;
  /** `unsupported: <construct>` findings (empty when encodable). */
  unsupported: string[];
  /** Encoding failure that is not a construct (size budget), when any. */
  note?: string;
  unroll: number;
  bounds: Bounds;
  inputs: number;
  /** Inputs whose encoder outcome was compared with the instrumented original. */
  compared: number;
  agreements: number;
  /** Compared outcomes by tag (the TypeScript side). */
  tags: { ok: number; throw: number; 'range-violation': number };
  /** Inputs where the encoder reached its unrolling bound (not compared). */
  fuel: number;
  /** Inputs where the TypeScript original faulted (not compared). */
  tsFaults: number;
  /** Inputs whose Z3 call did not answer (timeout/unknown; not compared). */
  solverMissing: number;
  uniquenessChecked: number;
  leanCompared: number;
  mismatches: SanityMismatch[];
  z3: Z3Info;
  smtChars: number;
  ms: number;
  solveMs: number;
}

function maxShape(inputs: Val[][], params: Ty[]): { array: number; string: number } {
  let array = 0;
  let string = 0;
  const visit = (v: Val, ty: Ty): void => {
    switch (ty.k) {
      case 'string':
        string = Math.max(string, (v as string).length);
        break;
      case 'array':
        array = Math.max(array, (v as Val[]).length);
        for (const x of v as Val[]) visit(x, ty.elem);
        break;
      case 'tuple':
        ty.elems.forEach((e, i) => visit((v as Val[])[i]!, e));
        break;
      case 'record':
        for (const f of ty.fields) visit((v as { [k: string]: Val })[f.name]!, f.ty);
        break;
      default:
        break;
    }
  };
  for (const args of inputs) args.forEach((a, i) => visit(a, params[i]!));
  return { array, string };
}

interface Built {
  smt: Smt;
  enc: Encoder;
  shared: Shared;
  inputs: SV[];
  out: ReturnType<Encoder['run']>;
  unroll: number;
}

function build(ir: IrProgram, params: Ty[], bounds: Bounds, unroll: number, maxChars: number): Built {
  const smt = new Smt({ maxChars });
  smt.emit('(set-option :produce-models true)');
  const shared: Shared = { msgs: [] };
  const ins = params.map((ty, i) => declareInput(smt, ty, bounds, `in${i}`));
  for (const x of ins) smt.assert(x.dom);
  const enc = new Encoder(smt, ir, { unroll, shared });
  const out = enc.run(ins.map((x) => x.v));
  return { smt, enc, shared, inputs: ins.map((x) => x.v), out, unroll };
}

/** Sanity-check the encoding of one translation. */
export async function sanityCheck(t: Translation, ir: IrProgram, z3: Z3Driver, opts: SanityOptions = {}): Promise<SanityReport> {
  const t0 = performance.now();
  const n = opts.n ?? 60;
  const gen = generateInputs(t, { n, seed: opts.seed ?? 20261005, maxArray: opts.maxArray ?? 6, maxString: opts.maxString ?? 8 });
  const inputs = gen.inputs;
  const params = t.params.map((p) => p.ty);
  const shape = maxShape(inputs, params);
  const bounds: Bounds = { array: shape.array, string: shape.string, int: 2 ** 53 };
  const report: SanityReport = {
    fnName: t.fnName,
    encodable: true,
    unsupported: [],
    unroll: 0,
    bounds,
    inputs: inputs.length,
    compared: 0,
    agreements: 0,
    tags: { ok: 0, throw: 0, 'range-violation': 0 },
    fuel: 0,
    tsFaults: 0,
    solverMissing: 0,
    uniquenessChecked: 0,
    leanCompared: 0,
    mismatches: [],
    z3: z3.info(),
    smtChars: 0,
    ms: 0,
    solveMs: 0,
  };

  // 1. encoding (lower the unrolling bound until it fits the size budget)
  let built: Built | null = null;
  let unroll = opts.unroll ?? 24;
  while (unroll >= 1) {
    try {
      built = build(ir, params, bounds, unroll, opts.maxChars ?? 8_000_000);
      break;
    } catch (e) {
      if (e instanceof Unsupported) {
        report.encodable = false;
        report.unsupported = [e.construct];
        report.ms = performance.now() - t0;
        return report;
      }
      if (!(e instanceof TooLarge)) throw e;
      unroll = unroll > 8 ? Math.floor((unroll * 2) / 3) : unroll - 1;
    }
  }
  if (!built) {
    report.note = 'encoding too large at every unrolling bound';
    report.ms = performance.now() - t0;
    return report;
  }
  report.unroll = built.unroll;
  report.smtChars = built.smt.size;

  // 2. TypeScript side
  const [ts] = await runInstrumented([t], inputs, { sandbox: opts.sandbox, perCallMs: 500 });

  // 3. Z3 side, chunked
  const base = built.smt.text();
  const terms = outcomeTerms(built.out);
  const enc: EncodedOutcome[] = inputs.map(() => ({ tag: 'fault', detail: 'not evaluated' }));
  const answered: boolean[] = inputs.map(() => false);
  const rawSt: bigint[] = inputs.map(() => 0n);
  // Each input gets the whole script after a (reset): with push/pop Z3 runs its incremental core without the
  // preprocessing that substitutes the input constants, and chains of div/mod then take minutes instead of ms.
  const chunk = Math.max(1, Math.min(opts.chunk ?? 30, Math.floor(30_000_000 / Math.max(base.length, 1))));
  const solveMs = opts.solveMs ?? 120_000;
  const inputAssert = (args: Val[]): string => and(...args.map((a, i) => eqConst(built!.inputs[i]!, a, params[i]!)));
  for (let s = 0; s < inputs.length; s += chunk) {
    const idx = inputs.map((_, i) => i).slice(s, s + chunk);
    const script =
      idx.map((i) => `(reset)\n${base}\n(assert ${inputAssert(inputs[i]!)})\n(check-sat)\n(get-value (${terms.join(' ')}))`).join('\n');
    const r = await z3.solve(script, { timeoutMs: solveMs });
    report.solveMs += r.ms;
    const { answers, errors } = readAnswers(transcript(r));
    if (errors.length) report.mismatches.push({ input: [], against: 'solver', expected: 'no solver error', encoder: errors.slice(0, 3).join(' | ') });
    idx.forEach((i, j) => {
      const a = answers[j];
      if (!a || a.status !== 'sat' || !a.values) {
        if (a && a.status === 'unsat') report.mismatches.push({ input: inputs[i]!, against: 'solver', expected: 'sat', encoder: 'unsat: the encoding admits no run on this input' });
        return;
      }
      answered[i] = true;
      const get = lookup(terms, a.values);
      rawSt[i] = get(built!.out.st) as bigint;
      enc[i] = decodeOutcome(built!.out, t.ret, built!.enc, built!.shared, get);
    });
  }

  // 4. uniqueness: no other status/output is consistent with the input
  const uniq = inputs.map((_, i) => i).filter((i) => answered[i]);
  for (let s = 0; s < uniq.length; s += chunk) {
    const idx = uniq.slice(s, s + chunk);
    const blocks = idx.map((i) => {
      const o = enc[i]!;
      const st = built!.out.st;
      const same = o.tag === 'ok' ? and(eq(st, '0'), eqConst(built!.out.v, o.value, t.ret)) : eq(st, int(rawSt[i]!));
      return `(reset)\n${base}\n(assert ${inputAssert(inputs[i]!)})\n(assert ${not(same)})\n(check-sat)`;
    });
    const r = await z3.solve(blocks.join('\n'), { timeoutMs: solveMs });
    report.solveMs += r.ms;
    const { answers, errors } = readAnswers(transcript(r));
    if (errors.length) report.mismatches.push({ input: [], against: 'solver', expected: 'no solver error', encoder: errors.slice(0, 3).join(' | ') });
    idx.forEach((i, j) => {
      const a = answers[j];
      if (!a) return;
      report.uniquenessChecked++;
      if (a.status !== 'unsat') report.mismatches.push({ input: inputs[i]!, against: 'uniqueness', expected: 'unsat (one output per input)', encoder: a.status });
    });
  }

  // 5. compare with the instrumented original
  const leanJobs: number[] = [];
  inputs.forEach((args, i) => {
    const o = ts![i]!;
    if (o.tag === 'fault') {
      report.tsFaults++;
      return;
    }
    if (!answered[i]) {
      report.solverMissing++;
      return;
    }
    const e = enc[i]!;
    if (e.tag === 'fuel') {
      report.fuel++;
      return;
    }
    report.compared++;
    report.tags[o.tag]++;
    if (outcomeEqual(o, e)) report.agreements++;
    else report.mismatches.push({ input: args, against: 'ts', expected: o, encoder: e });
    leanJobs.push(i);
  });

  // 6. optional: Lean checked twin
  if (opts.lean && leanJobs.length) {
    const res = await opts.lean.evalBatch(
      t.lean.source,
      leanJobs.map((i) => leanChkEvalExpr(t, inputs[i]!)),
      { budgetMs: 180_000 },
    );
    leanJobs.forEach((i, j) => {
      const raw = res.outputs[j];
      if (raw === null || raw === undefined || res.errors.has(j)) return;
      const lo = parseLeanOutcome(raw);
      report.leanCompared++;
      if (!outcomeEqual(lo, enc[i] as Outcome)) report.mismatches.push({ input: inputs[i]!, against: 'lean', expected: lo, encoder: enc[i]! });
    });
  }
  report.ms = performance.now() - t0;
  return report;
}

export interface CorpusSanityReport {
  functions: number;
  encodable: number;
  /** construct -> corpus ids */
  unsupported: Record<string, string[]>;
  inputs: number;
  compared: number;
  agreements: number;
  fuel: number;
  tsFaults: number;
  solverMissing: number;
  mismatches: number;
  leanCompared: number;
  reports: Array<SanityReport & { id: string }>;
  z3: Z3Info;
  ms: number;
}

/** Sanity mode over every in-subset corpus function (CLI-callable). */
export async function sanityReport(corpusRoot: string, z3: Z3Driver, opts: SanityOptions = {}): Promise<CorpusSanityReport> {
  const t0 = performance.now();
  const out: CorpusSanityReport = {
    functions: 0,
    encodable: 0,
    unsupported: {},
    inputs: 0,
    compared: 0,
    agreements: 0,
    fuel: 0,
    tsFaults: 0,
    solverMissing: 0,
    mismatches: 0,
    leanCompared: 0,
    reports: [],
    z3: z3.info(),
    ms: 0,
  };
  for (const e of loadCorpus(corpusRoot)) {
    const w = translateWithIr(e.source, e.fnName);
    if (!w.result.ok || !w.ir) continue;
    out.functions++;
    const r = await sanityCheck(w.result, w.ir, z3, opts);
    out.reports.push({ ...r, id: e.id });
    if (r.encodable) out.encodable++;
    for (const u of r.unsupported) (out.unsupported[u] ??= []).push(e.id);
    out.inputs += r.inputs;
    out.compared += r.compared;
    out.agreements += r.agreements;
    out.fuel += r.fuel;
    out.tsFaults += r.tsFaults;
    out.solverMissing += r.solverMissing;
    out.mismatches += r.mismatches.length;
    out.leanCompared += r.leanCompared;
  }
  out.ms = performance.now() - t0;
  return out;
}
