import Faithful.Tactics

-- Faithful: fibonacci. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:9dda966bf54dd6ee706e54735d675983f9220f36dc9a034f4e7d4789bb0c4fbe

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibonacci (n : Int) : Except String (Int) :=
  do
    if (n < (0 : Int)) then
      throw "n must be non-negative"
    else
      if (n < (2 : Int)) then
        pure n
      else
        let τ1 ← Model.fibonacci (n - (1 : Int))
        let τ2 ← Model.fibonacci (n - (2 : Int))
        pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibonacci_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (0 : Int)) then
      throw (Faithful.Fail.thrown "n must be non-negative")
    else
      if (n < (2 : Int)) then
        pure n
      else
        Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 16: n - 1"
        Faithful.ck (decide (τd < 500)) "depth check failed at line 16: fibonacci(n - 1)"
        let τ1 ← Model.fibonacci_chkD (τd + 1) (n - (1 : Int))
        Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 16: n - 2"
        Faithful.ck (decide (τd < 500)) "depth check failed at line 16: fibonacci(n - 2)"
        let τ2 ← Model.fibonacci_chkD (τd + 1) (n - (2 : Int))
        Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 16: fibonacci(n - 1) + fibonacci(n - 2)"
        pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibonacci_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibonacci_chkD 1 n

def fibonacci_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibonacci_chk n)

def fibonacci_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibonacci_rangeOk n)

end Model

-- agreed spec
namespace Spec

def fib : Nat → Nat
  | 0 => 0
  | 1 => 1
  | n + 2 => fib (n + 1) + fib n

def spec (n : Int) : Except String (Int) :=
  if n < 0 then
    .error "n must be non-negative"
  else
    .ok (Int.ofNat (fib n.toNat))

end Spec

theorem fibonacci_eq_spec (n : Int) : Model.fibonacci n = Spec.spec n := by
  refine Model.fibonacci.induct (motive := fun n => Model.fibonacci n = Spec.spec n) ?_ ?_ ?_ n
  · intro x hx
    simp [Model.fibonacci, Spec.spec, hx]
  · intro x hx0 hx2
    have hx_cases : x = 0 ∨ x = 1 := by omega
    rcases hx_cases with rfl | rfl <;> simp [Model.fibonacci, Spec.spec, Spec.fib]
  · intro x hx0 hx2 ih1 ih2
    rw [Model.fibonacci]
    simp only [if_neg (by omega : ¬ x < 0), if_neg (by omega : ¬ x < 2),
      Faithful.except_pure_eq_ok, Faithful.except_ok_bind]
    rw [ih1, ih2]
    have h1 : (x - 1).toNat = (x - 2).toNat + 1 := by omega
    have h2 : x.toNat = (x - 2).toNat + 2 := by omega
    simp [Spec.spec, Spec.fib, h1, h2,
      show ¬ x < 1 by omega, show ¬ x < 2 by omega, hx0]

theorem original_meets_spec : ∀ (n : Int), Model.fibonacci_pre n = true → (match Model.fibonacci n with | .ok _ => true | .error _ => false) = true → Model.fibonacci n = Spec.spec n :=
by
  intro n _ _
  exact fibonacci_eq_spec n

#print axioms original_meets_spec
