import Faithful.Tactics

-- Faithful: fibRecursive. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:8926a25bdd8c147f9347e1d2fd39e1e13532021f3d2d2c64e061fd2570ed6e8d

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibRecursive (n : Int) : Int :=
  (if (n < (2 : Int)) then
    n
   else
    ((Model.fibRecursive (n - (1 : Int))) + (Model.fibRecursive (n - (2 : Int)))))
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (2 : Int)) then
      pure n
    else
      Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 11: n - 1"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 1)"
      let τ1 ← Model.fibRecursive_chkD (τd + 1) (n - (1 : Int))
      Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 11: n - 2"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 2)"
      let τ2 ← Model.fibRecursive_chkD (τd + 1) (n - (2 : Int))
      Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 11: fibRecursive(n - 1) + fibRecursive(n - 2)"
      pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibRecursive_chkD 1 n

def fibRecursive_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibRecursive_chk n)

def fibRecursive_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibRecursive_rangeOk n)

end Model

-- agreed spec
namespace Spec

def fibAux : Nat → Nat → Nat
  | 0, _ => 0
  | 1, _ => 1
  | k + 2, fuel =>
      if fuel = 0 then 0 else fibAux (k + 1) (fuel - 1) + fibAux k (fuel - 1)

def spec (n : Int) : Int :=
  if n < 0 then n
  else Int.ofNat (fibAux n.toNat n.toNat)

end Spec

theorem fibAux_fuel_ge (k fuel : Nat) (h : k ≤ fuel) :
    Spec.fibAux k fuel = Spec.fibAux k k := by
  induction k using Nat.strong_induction_on generalizing fuel with
  | h k ih =>
      cases k with
      | zero => simp [Spec.fibAux]
      | succ k =>
          cases k with
          | zero => simp [Spec.fibAux]
          | succ k =>
              cases fuel with
              | zero => omega
              | succ fuel =>
                  have h₁ : k + 1 ≤ fuel := by omega
                  have h₂ : k ≤ fuel := by omega
                  have hs₁ : fuel + 1 - 1 = fuel := by omega
                  have hs₂ : k + 2 - 1 = k + 1 := by omega
                  rw [Spec.fibAux, Spec.fibAux]
                  simp only [if_neg (by omega : ¬ (fuel + 1 : Nat) = 0),
                    if_neg (by omega : ¬ (k + 2 : Nat) = 0)]
                  rw [hs₁, hs₂]
                  rw [ih (k + 1) (by omega) fuel h₁, ih k (by omega) fuel h₂,
                    ih k (by omega) (k + 1) (by omega)]

theorem spec_fib_recur (x : Int) (hx : 2 ≤ x) :
    Spec.spec x = Spec.spec (x - 1) + Spec.spec (x - 2) := by
  obtain ⟨n, rfl⟩ : ∃ n : Nat, x = (n : Int) := ⟨x.toNat, by omega⟩
  obtain ⟨k, rfl⟩ : ∃ k : Nat, n = k + 2 := ⟨n - 2, by omega⟩
  have hleft : Spec.fibAux (k + 2) (k + 2) =
      Spec.fibAux (k + 1) (k + 1) + Spec.fibAux k k := by
    rw [Spec.fibAux]
    simp only [if_neg (by omega : ¬ (k + 2 : Nat) = 0)]
    have hs : k + 2 - 1 = k + 1 := by omega
    rw [hs]
    have h₂ := fibAux_fuel_ge k (k + 1) (by omega)
    rw [h₂]
  have hsub1 : (((k + 2 : Nat) : Int) - 1).toNat = k + 1 := by omega
  have hsub2 : (((k + 2 : Nat) : Int) - 2).toNat = k := by omega
  simp only [Spec.spec, if_neg (by omega : ¬ (↑(k + 2 : Nat) : Int) < 0), Int.toNat_natCast,
    if_neg (by omega : ¬ ((↑(k + 2 : Nat) : Int) - 1) < 0),
    if_neg (by omega : ¬ ((↑(k + 2 : Nat) : Int) - 2) < 0)]
  rw [hsub1, hsub2, hleft]
  simp

theorem original_meets_spec : ∀ (n : Int), Model.fibRecursive_pre n = true → Model.fibRecursive n = Spec.spec n :=
by
  intro n _
  have hrec (x : Int) : Model.fibRecursive x = Spec.spec x := by
    fun_induction Model.fibRecursive x with
    | case1 y hy =>
        by_cases hneg : y < 0
        · simp [Spec.spec, hneg]
        · have hy' : y = 0 ∨ y = 1 := by omega
          rcases hy' with rfl | rfl <;> simp [Spec.spec, Spec.fibAux]
    | case2 y hy ih₁ ih₂ =>
        rw [ih₁, ih₂, spec_fib_recur y (by omega)]
  exact hrec n

#print axioms original_meets_spec
