import Faithful.Tactics

-- Faithful: fibRecursive. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:776eb987ef4889f5729e11bf4658f0cf3623ebafdc69064cf2a14cf4c423cc63

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibRecursive (n : Int) : Int :=
  (if (n < (2 : Int)) then
    n
   else
    ((Model.fibRecursive (n - (1 : Int))) + (Model.fibRecursive (n - (2 : Int)))))
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (2 : Int)) then
      pure n
    else
      Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 11: n - 1"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 1)"
      let τ1 ← Model.fibRecursive_chkD (τd + 1) (n - (1 : Int))
      Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 11: n - 2"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 2)"
      let τ2 ← Model.fibRecursive_chkD (τd + 1) (n - (2 : Int))
      Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 11: fibRecursive(n - 1) + fibRecursive(n - 2)"
      pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibRecursive_chkD 1 n

def fibRecursive_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibRecursive_chk n)

def fibRecursive_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibRecursive_rangeOk n)

end Model

-- agreed spec
namespace Spec

def fibAux : Nat → Nat
  | 0 => 0
  | 1 => 1
  | n + 2 => fibAux (n + 1) + fibAux n

def spec (n : Int) : Int :=
  if n < 2 then n else Int.ofNat (fibAux n.toNat)

end Spec

theorem spec_nat_eq (k : Nat) : Spec.spec (k : Int) = (Spec.fibAux k : Int) := by
  cases k with
  | zero => simp [Spec.spec, Spec.fibAux]
  | succ k =>
    cases k with
    | zero => simp [Spec.spec, Spec.fibAux]
    | succ k =>
      have hn : ¬ ((k : Int) + 1 + 1 < 2) := by omega
      have ht : (((k : Int) + 1 + 1).toNat) = k + 2 := by omega
      simp [Spec.spec, hn, ht, Spec.fibAux]

theorem spec_fib_recurrence (n : Int) (h : 2 ≤ n) :
    Spec.spec n = Spec.spec (n - 1) + Spec.spec (n - 2) := by
  let k := (n - 2).toNat
  have hk : n = ((k + 2 : Nat) : Int) := by dsimp [k]; omega
  have h1 : n - 1 = ((k + 1 : Nat) : Int) := by omega
  have h2 : n - 2 = (k : Int) := by omega
  calc
    Spec.spec n = (Spec.fibAux (k + 2) : Int) := by
      rw [hk]
      exact spec_nat_eq (k + 2)
    _ = Spec.spec (n - 1) + Spec.spec (n - 2) := by
      rw [h1, h2, spec_nat_eq (k + 1), spec_nat_eq k]
      simp [Spec.fibAux]

theorem fibRecursive_eq_spec (n : Int) : Model.fibRecursive n = Spec.spec n := by
  fun_induction Model.fibRecursive n with
  | case1 x hx =>
      simp [Spec.spec, hx]
  | case2 x hx ih1 ih2 =>
      rw [ih1, ih2]
      exact (spec_fib_recurrence x (by omega)).symm

theorem original_meets_spec : ∀ (n : Int), Model.fibRecursive_pre n = true → Model.fibRecursive n = Spec.spec n :=
by
  intro n _
  exact fibRecursive_eq_spec n

#print axioms original_meets_spec
