import Faithful.Tactics

-- Faithful: fibRecursive. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:6059e182ae9ba784866272a82d4bc62666dfb85abfb3ca99132a7855a0e8b47b

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibRecursive (n : Int) : Int :=
  (if (n < (2 : Int)) then
    n
   else
    ((Model.fibRecursive (n - (1 : Int))) + (Model.fibRecursive (n - (2 : Int)))))
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (2 : Int)) then
      pure n
    else
      Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 11: n - 1"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 1)"
      let τ1 ← Model.fibRecursive_chkD (τd + 1) (n - (1 : Int))
      Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 11: n - 2"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 2)"
      let τ2 ← Model.fibRecursive_chkD (τd + 1) (n - (2 : Int))
      Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 11: fibRecursive(n - 1) + fibRecursive(n - 2)"
      pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibRecursive_chkD 1 n

def fibRecursive_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibRecursive_chk n)

def fibRecursive_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibRecursive_rangeOk n)

end Model

-- agreed spec
namespace Spec

def fib (n : Nat) : Nat :=
  match n with
  | 0 => 0
  | 1 => 1
  | k + 2 => fib (k + 1) + fib k

def spec (n : Int) : Int :=
  if n < 2 then n else Int.ofNat (fib n.toNat)

end Spec

theorem spec_nat_cast (k : Nat) : Spec.spec (k : Int) = Int.ofNat (Spec.fib k) := by
  cases k with
  | zero => simp [Spec.spec, Spec.fib]
  | succ k =>
    cases k with
    | zero => simp [Spec.spec, Spec.fib]
    | succ k =>
      have h : ¬ ((k + 2 : Nat) : Int) < 2 := by omega
      rw [Spec.spec]
      simp only [if_neg h]
      have ht : (((k + 2 : Nat) : Int).toNat) = k + 2 := by omega
      rw [ht]

theorem spec_rec (x : Int) (hx : 2 ≤ x) :
    Spec.spec x = Spec.spec (x - 1) + Spec.spec (x - 2) := by
  obtain ⟨k, hk⟩ : ∃ k : Nat, x = ((k + 2 : Nat) : Int) :=
    ⟨x.toNat - 2, by omega⟩
  subst x
  have h1 : ((k + 2 : Nat) : Int) - 1 = ((k + 1 : Nat) : Int) := by omega
  have h2 : ((k + 2 : Nat) : Int) - 2 = (k : Int) := by omega
  rw [h1, h2]
  rw [spec_nat_cast (k + 2), spec_nat_cast (k + 1), spec_nat_cast k]
  simp [Spec.fib]

theorem fib_eq_spec (n : Int) : Model.fibRecursive n = Spec.spec n := by
  induction n using Model.fibRecursive.induct with
  | case1 x hx =>
      rw [Model.fibRecursive]
      simp [hx, Spec.spec]
  | case2 x hx ih1 ih2 =>
      rw [Model.fibRecursive]
      rw [if_neg hx]
      rw [ih1, ih2]
      exact (spec_rec x (by omega)).symm

theorem original_meets_spec : ∀ (n : Int), Model.fibRecursive_pre n = true → Model.fibRecursive n = Spec.spec n :=
by
  intro n _
  exact fib_eq_spec n

#print axioms original_meets_spec
