import Faithful.Tactics

-- Faithful: fibRecursive. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:03c1b889e00b04b19528f73949e4cbca3b0fd1901e39735a3be617ec2264fbad

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibRecursive (n : Int) : Int :=
  (if (n < (2 : Int)) then
    n
   else
    ((Model.fibRecursive (n - (1 : Int))) + (Model.fibRecursive (n - (2 : Int)))))
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (2 : Int)) then
      pure n
    else
      Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 11: n - 1"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 1)"
      let τ1 ← Model.fibRecursive_chkD (τd + 1) (n - (1 : Int))
      Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 11: n - 2"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 2)"
      let τ2 ← Model.fibRecursive_chkD (τd + 1) (n - (2 : Int))
      Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 11: fibRecursive(n - 1) + fibRecursive(n - 2)"
      pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibRecursive_chkD 1 n

def fibRecursive_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibRecursive_chk n)

def fibRecursive_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibRecursive_rangeOk n)

end Model

-- agreed spec
namespace Spec

def spec (n : Int) : Int :=
  if n < 2 then n else
    let rec fib : Nat → Int
      | 0 => 0
      | 1 => 1
      | k + 2 => fib (k + 1) + fib k
    fib n.toNat

end Spec

theorem spec_step (n : Int) (hn : 2 ≤ n) :
    Spec.spec (n - 1) + Spec.spec (n - 2) = Spec.spec n := by
  obtain ⟨k, rfl⟩ : ∃ k : Nat, n = (k : Int) := ⟨n.toNat, by omega⟩
  have hk : 2 ≤ k := by omega
  obtain ⟨m, rfl⟩ : ∃ m : Nat, k = m + 2 := ⟨k - 2, by omega⟩
  have h1 : ((↑(m + 2) : Int) - 1) = (↑(m + 1) : Int) := by omega
  have h2 : ((↑(m + 2) : Int) - 2) = (↑m : Int) := by omega
  rw [h1, h2]
  cases m with
  | zero => norm_num [Spec.spec, Spec.spec.fib]
  | succ m =>
      cases m with
      | zero => norm_num [Spec.spec, Spec.spec.fib]
      | succ m =>
          have h1 : ¬ ((↑(m + 3) : Int) < 2) := by
            exact_mod_cast (show ¬ (m + 3 < 2) by omega)
          have h2 : ¬ ((↑(m + 2) : Int) < 2) := by
            exact_mod_cast (show ¬ (m + 2 < 2) by omega)
          have h3 : ¬ ((↑(m + 4) : Int) < 2) := by
            exact_mod_cast (show ¬ (m + 4 < 2) by omega)
          simp only [Spec.spec, h1, h2, h3, ↓reduceIte, Int.toNat_natCast, Spec.spec.fib]

theorem fibRecursive_eq_spec (n : Int) : Model.fibRecursive n = Spec.spec n := by
  fun_induction Model.fibRecursive n with
  | case1 x hx =>
      simp [Model.fibRecursive, hx, Spec.spec]
  | case2 x hx ih1 ih2 =>
      have hx2 : 2 ≤ x := by omega
      change Model.fibRecursive (x - 1) + Model.fibRecursive (x - 2) = Spec.spec x
      rw [ih1, ih2]
      exact spec_step x hx2

theorem original_meets_spec : ∀ (n : Int), Model.fibRecursive_pre n = true → Model.fibRecursive n = Spec.spec n :=
by
  intro n _
  exact fibRecursive_eq_spec n

#print axioms original_meets_spec
