import Faithful.Tactics

-- Faithful: aliquotSum. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:405b5528d7931c2cd33d69ea2df8b1a94d7d120fb990d637eae08edfb6355ff1

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def aliquotSum_loop1 (n : Int) (sum : Int) (i : Int) : (Int × Int) :=
  (if (i < n) then
    (let sum_2 := (if ((Int.tmod n i) = (0 : Int)) then
          (let sum_1 := (sum + i);
           sum_1)
         else
          sum);
     (let i_1 := (i + (1 : Int));
      (Model.aliquotSum_loop1 n sum_2 i_1)))
   else
    (sum, i))
termination_by ((n - i)).toNat
decreasing_by
  faithful_decreasing

def aliquotSum (n : Int) : Int :=
  (let sum := (0 : Int);
   (let i := (1 : Int);
    (let (sum_1, i_1) := (Model.aliquotSum_loop1 n sum i);
     sum_1)))

def aliquotSum_loop1_chk (n : Int) (sum : Int) (i : Int) : Faithful.Chk ((Int × Int)) :=
  do
    if (i < n) then
      let τ1 ← do
          Faithful.ck (decide (i ≠ 0)) "nonzero check failed at line 12: n % i"
          if ((Int.tmod n i) = (0 : Int)) then
            Faithful.ck (Faithful.inRange (sum + i)) "range check failed at line 13: sum + i"
            let sum_1 := (sum + i)
            pure sum_1
          else
            pure sum
      let sum_2 := τ1
      Faithful.ck (Faithful.inRange (i + (1 : Int))) "range check failed at line 11: i++"
      let i_1 := (i + (1 : Int))
      Model.aliquotSum_loop1_chk n sum_2 i_1
    else
      pure (sum, i)
termination_by ((n - i)).toNat
decreasing_by
  faithful_decreasing

def aliquotSum_chk (n : Int) : Faithful.Chk (Int) :=
  do
    let sum := (0 : Int)
    let i := (1 : Int)
    let τ1 ← Model.aliquotSum_loop1_chk n sum i
    let (sum_1, i_1) := τ1
    pure sum_1

def aliquotSum_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.aliquotSum_chk n)

def aliquotSum_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.aliquotSum_rangeOk n)

end Model

-- candidate model
-- candidate model
set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def aliquotSum_cand_loop1 (n : Int) (limit : Int) (sum : Int) (i : Int) : (Int × Int) :=
  (if (i ≤ limit) then
    (let sum_2 := (if ((Int.tmod n i) = (0 : Int)) then
          (let sum_1 := (sum + i);
           sum_1)
         else
          sum);
     (let i_1 := (i + (1 : Int));
      (Model.aliquotSum_cand_loop1 n limit sum_2 i_1)))
   else
    (sum, i))
termination_by (((limit - i) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def aliquotSum_cand (n : Int) : Int :=
  (if (n ≤ (1 : Int)) then
    (0 : Int)
   else
    (let sum := (1 : Int);
     (let limit := (Int.fdiv n (2 : Int));
      (let i := (2 : Int);
       (let (sum_1, i_1) := (Model.aliquotSum_cand_loop1 n limit sum i);
        sum_1)))))

def aliquotSum_cand_loop1_chk (n : Int) (limit : Int) (sum : Int) (i : Int) : Faithful.Chk ((Int × Int)) :=
  do
    if (i ≤ limit) then
      let τ1 ← do
          Faithful.ck (decide (i ≠ 0)) "nonzero check failed at line 7: n % i"
          if ((Int.tmod n i) = (0 : Int)) then
            Faithful.ck (Faithful.inRange (sum + i)) "range check failed at line 7: sum += i"
            let sum_1 := (sum + i)
            pure sum_1
          else
            pure sum
      let sum_2 := τ1
      Faithful.ck (Faithful.inRange (i + (1 : Int))) "range check failed at line 6: i++"
      let i_1 := (i + (1 : Int))
      Model.aliquotSum_cand_loop1_chk n limit sum_2 i_1
    else
      pure (sum, i)
termination_by (((limit - i) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def aliquotSum_cand_chk (n : Int) : Faithful.Chk (Int) :=
  do
    if (n ≤ (1 : Int)) then
      pure (0 : Int)
    else
      let sum := (1 : Int)
      Faithful.ck (decide ((2 : Int) ≠ 0)) "nonzero check failed at line 5: Math.floor(n / 2)"
      let limit := (Int.fdiv n (2 : Int))
      let i := (2 : Int)
      let τ1 ← Model.aliquotSum_cand_loop1_chk n limit sum i
      let (sum_1, i_1) := τ1
      pure sum_1

def aliquotSum_cand_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.aliquotSum_cand_chk n)

def aliquotSum_cand_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.aliquotSum_cand_rangeOk n)

end Model

-- agreed spec
namespace Spec

def spec (n : Int) : Int :=
  ((List.range (n - 1).toNat).filterMap fun k =>
    let d := (k + 1 : Nat)
    if n > 1 && (n % (d : Int) == 0) then some (d : Int) else none).foldl (· + ·) 0

end Spec

theorem aliquotSum_loop1_of_le (n : Int) : ∀ (sum i : Int), n ≤ i → (Model.aliquotSum_loop1 n sum i).1 = sum := by
  intro sum i
  fun_induction Model.aliquotSum_loop1 n sum i with
  | case1 sum i h sum_2 i_1 ih =>
      intro hi
      omega
  | case2 sum i h =>
      intro hi
      simp [Model.aliquotSum_loop1, h]

theorem original_meets_spec : ∀ (n : Int), Model.aliquotSum_pre n = true → decide (n ≠ 0) = true → decide (n ≤ 0) = true → Model.aliquotSum n = Spec.spec n :=
by
  intro n _ _ hle
  have hn : n ≤ 0 := of_decide_eq_true hle
  have hzero : (n - 1).toNat = 0 := by omega
  have hspec : Spec.spec n = 0 := by
    unfold Spec.spec
    simp [hzero]
  simp only [Model.aliquotSum]
  rw [aliquotSum_loop1_of_le n 0 1 (by omega)]
  exact hspec.symm

theorem candidate_5_equals_spec : ∀ (n : Int), Model.aliquotSum_pre n = true → decide (n ≠ 0) = true → decide (n ≤ 0) = true → Model.aliquotSum_cand n = Spec.spec n :=
by
  intro n _ _ hle
  have hn : n ≤ 0 := of_decide_eq_true hle
  have hzero : (n - 1).toNat = 0 := by omega
  have hspec : Spec.spec n = 0 := by
    unfold Spec.spec
    simp [hzero]
  have hcond : n ≤ 1 := by omega
  simp [Model.aliquotSum_cand, hcond, hspec]

theorem candidate_5_range_ok : ∀ (n : Int), Model.aliquotSum_pre n = true → decide (n ≠ 0) = true → decide (n ≤ 0) = true → Model.aliquotSum_cand_pre n = true :=
by
  intro n hpre _ hle
  simp only [Model.aliquotSum_pre, Bool.and_eq_true] at hpre
  have hn : n ≤ 0 := of_decide_eq_true hle
  have hcond : n ≤ 1 := by omega
  simp [Model.aliquotSum_cand_pre, Model.aliquotSum_cand_rangeOk,
    Model.aliquotSum_cand_chk, hcond, hpre.1]

theorem candidate_5_meets_spec : ∀ (n : Int), Model.aliquotSum_pre n = true → decide (n ≠ 0) = true → decide (n ≤ 0) = true → Model.aliquotSum_cand_pre n = true ∧ Model.aliquotSum_cand n = Spec.spec n :=
by
  intro n h_c1 h_c2 h_c3
  exact ⟨candidate_5_range_ok n h_c1 h_c2 h_c3, candidate_5_equals_spec n h_c1 h_c2 h_c3⟩

#print axioms original_meets_spec
#print axioms candidate_5_meets_spec
