import Faithful.Tactics

-- Faithful: fibRecursive. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:673141cc132579355d9de0f39f104d3e6115a0847544b6023fdb7ded60be98bf

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibRecursive (n : Int) : Int :=
  (if (n < (2 : Int)) then
    n
   else
    ((Model.fibRecursive (n - (1 : Int))) + (Model.fibRecursive (n - (2 : Int)))))
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (2 : Int)) then
      pure n
    else
      Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 11: n - 1"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 1)"
      let τ1 ← Model.fibRecursive_chkD (τd + 1) (n - (1 : Int))
      Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 11: n - 2"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 2)"
      let τ2 ← Model.fibRecursive_chkD (τd + 1) (n - (2 : Int))
      Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 11: fibRecursive(n - 1) + fibRecursive(n - 2)"
      pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibRecursive_chkD 1 n

def fibRecursive_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibRecursive_chk n)

def fibRecursive_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibRecursive_rangeOk n)

end Model

-- agreed spec
namespace Spec

def spec (n : Int) : Int :=
  if n < 2 then n
  else
    let rec fib (k : Nat) : Nat :=
      match k with
      | 0 => 0
      | 1 => 1
      | k + 2 => fib (k + 1) + fib k
    (fib n.toNat : Int)

end Spec

theorem spec_fib_step (n : Int) (hn : 2 ≤ n) :
    Spec.spec (n - 1) + Spec.spec (n - 2) = Spec.spec n := by
  by_cases h2 : n = 2
  · subst n
    norm_num [Spec.spec, Spec.spec.fib]
  by_cases h3 : n = 3
  · subst n
    norm_num [Spec.spec, Spec.spec.fib]
  have hn4 : 4 ≤ n := by omega
  have hN : ¬ n < 2 := by omega
  have h1 : ¬ n - 1 < 2 := by omega
  have h2' : ¬ n - 2 < 2 := by omega
  have ht : n.toNat = (n - 2).toNat + 2 := by omega
  have ht1 : (n - 1).toNat = (n - 2).toNat + 1 := by omega
  simp [Spec.spec, Spec.spec.fib, hN, h1, h2', ht, ht1]

theorem fibRecursive_eq_spec (n : Int) : Model.fibRecursive n = Spec.spec n := by
  fun_induction Model.fibRecursive n with
  | case1 x hx =>
      simp [Model.fibRecursive, Spec.spec, hx]
  | case2 x hx ih1 ih2 =>
      rw [ih1, ih2]
      exact spec_fib_step x (by omega)

theorem original_meets_spec : ∀ (n : Int), Model.fibRecursive_pre n = true → Model.fibRecursive n = Spec.spec n :=
by
  intro n _
  exact fibRecursive_eq_spec n

#print axioms original_meets_spec
