import Faithful.Tactics

-- Faithful: fibRecursive. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:25b825dc442ada1d678b98b33c568f925404fae480f4e282774b70a14bc3a078

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

def fibRecursive (n : Int) : Int :=
  (if (n < (2 : Int)) then
    n
   else
    ((Model.fibRecursive (n - (1 : Int))) + (Model.fibRecursive (n - (2 : Int)))))
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chkD (τd : Nat) (n : Int) : Faithful.Chk (Int) :=
  do
    if (n < (2 : Int)) then
      pure n
    else
      Faithful.ck (Faithful.inRange (n - (1 : Int))) "range check failed at line 11: n - 1"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 1)"
      let τ1 ← Model.fibRecursive_chkD (τd + 1) (n - (1 : Int))
      Faithful.ck (Faithful.inRange (n - (2 : Int))) "range check failed at line 11: n - 2"
      Faithful.ck (decide (τd < 500)) "depth check failed at line 11: fibRecursive(n - 2)"
      let τ2 ← Model.fibRecursive_chkD (τd + 1) (n - (2 : Int))
      Faithful.ck (Faithful.inRange (τ1 + τ2)) "range check failed at line 11: fibRecursive(n - 1) + fibRecursive(n - 2)"
      pure (τ1 + τ2)
termination_by (((n - (2 : Int)) + (1 : Int))).toNat
decreasing_by
  faithful_decreasing

def fibRecursive_chk (n : Int) : Faithful.Chk (Int) :=
  Model.fibRecursive_chkD 1 n

def fibRecursive_rangeOk (n : Int) : Bool := Faithful.rangeOkOf (Model.fibRecursive_chk n)

def fibRecursive_pre (n : Int) : Bool :=
  ((Faithful.intOk n)) && (Model.fibRecursive_rangeOk n)

end Model

-- agreed spec
namespace Spec

def fibNat : Nat → Nat
  | 0 => 0
  | 1 => 1
  | n + 2 => fibNat (n + 1) + fibNat n

def spec (n : Int) : Int :=
  if n < 0 then n else Int.ofNat (fibNat n.toNat)

end Spec

theorem fibRecursive_natCast (n : Nat) :
    Model.fibRecursive (n : Int) = (Spec.fibNat n : Int) := by
  induction n using Spec.fibNat.induct with
  | case1 => norm_num [Model.fibRecursive, Spec.fibNat]
  | case2 => norm_num [Model.fibRecursive, Spec.fibNat]
  | case3 n ih1 ih0 =>
      rw [Model.fibRecursive]
      have hn : ¬ ((n.succ.succ : Nat) : Int) < 2 := by omega
      rw [if_neg hn]
      have h1 : ((n.succ.succ : Nat) : Int) - 1 = (n.succ : Nat) := by omega
      have h2 : ((n.succ.succ : Nat) : Int) - 2 = (n : Nat) := by omega
      rw [h1, h2, ih1, ih0]
      simp [Spec.fibNat]

theorem original_meets_spec : ∀ (n : Int), Model.fibRecursive_pre n = true → Model.fibRecursive n = Spec.spec n :=
by
  intro n _
  by_cases hn : n < 0
  · have h2 : n < 2 := by omega
    rw [Model.fibRecursive, if_pos h2]
    simp [Spec.spec, hn]
  · have hc : n = (n.toNat : Int) := by omega
    calc
      Model.fibRecursive n = Model.fibRecursive (n.toNat : Int) :=
        congrArg Model.fibRecursive hc
      _ = (Spec.fibNat n.toNat : Int) := fibRecursive_natCast n.toNat
      _ = Spec.spec n := by simp [Spec.spec, hn]

#print axioms original_meets_spec
