import Faithful.Tactics

-- Faithful: spread. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:96f4e4d02b92d9e356d41fb4209697ed3786de6c4eaebc18fae21bd29d3ac5b4

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

structure Rec1 where
  count : Int
  min_ : Int
  max_ : Int
  range : Int
  deriving Repr, Inhabited

instance : Lean.ToJson Rec1 := ⟨fun r => Lean.Json.mkObj [("count", Faithful.jInt r.count), ("min", Faithful.jInt r.min_), ("max", Faithful.jInt r.max_), ("range", Faithful.jInt r.range)]⟩

def spread_loop1 (rest : List (Int)) (lo : Int) (hi : Int) : (Int × Int) :=
  (match rest with
   | [] =>
      (lo, hi)
   | x :: rest_1 =>
      (let lo_2 := (if (x < lo) then
            (let lo_1 := x;
             lo_1)
           else
            lo);
       (let hi_2 := (if (x > hi) then
             (let hi_1 := x;
              hi_1)
            else
             hi);
        (Model.spread_loop1 rest_1 lo_2 hi_2))))
termination_by rest.length
decreasing_by
  faithful_decreasing

def spread (xs : List (Int)) : Option (Model.Rec1) :=
  (if (((xs).length : Int) = (0 : Int)) then
    (none : Option (Model.Rec1))
   else
    (let lo := (Faithful.getD xs (0 : Int));
     (let hi := (Faithful.getD xs (0 : Int));
      (let xs_1 := xs;
       (let (lo_1, hi_1) := (Model.spread_loop1 xs_1 lo hi);
        (some ({ count := ((xs).length : Int), min_ := lo_1, max_ := hi_1, range := (hi_1 - lo_1) } : Model.Rec1)))))))

def spread_loop1_chk (rest : List (Int)) (lo : Int) (hi : Int) : Faithful.Chk ((Int × Int)) :=
  do
    match rest with
    | [] =>
      pure (lo, hi)
    | x :: rest_1 =>
      let lo_2 := (if (x < lo) then
              (let lo_1 := x;
               lo_1)
             else
              lo)
      let hi_2 := (if (x > hi) then
              (let hi_1 := x;
               hi_1)
             else
              hi)
      Model.spread_loop1_chk rest_1 lo_2 hi_2
termination_by rest.length
decreasing_by
  faithful_decreasing

def spread_chk (xs : List (Int)) : Faithful.Chk (Option (Model.Rec1)) :=
  do
    if (((xs).length : Int) = (0 : Int)) then
      pure (none : Option (Model.Rec1))
    else
      Faithful.ck (Faithful.inBounds xs (0 : Int)) "bounds check failed at line 14: xs[0]"
      let lo := (Faithful.getD xs (0 : Int))
      Faithful.ck (Faithful.inBounds xs (0 : Int)) "bounds check failed at line 15: xs[0]"
      let hi := (Faithful.getD xs (0 : Int))
      let xs_1 := xs
      let τ1 ← Model.spread_loop1_chk xs_1 lo hi
      let (lo_1, hi_1) := τ1
      Faithful.ck (Faithful.inRange (hi_1 - lo_1)) "range check failed at line 24: hi - lo"
      pure (some ({ count := ((xs).length : Int), min_ := lo_1, max_ := hi_1, range := (hi_1 - lo_1) } : Model.Rec1))

def spread_rangeOk (xs : List (Int)) : Bool := Faithful.rangeOkOf (Model.spread_chk xs)

def spread_pre (xs : List (Int)) : Bool :=
  (((xs).all (fun e0 => Faithful.intOk e0))) && (Model.spread_rangeOk xs)

end Model

-- agreed spec
namespace Spec

def spec (xs : List (Int)) : Option (Model.Rec1) :=
  match xs with
  | [] => none
  | first :: rest =>
      let minMax := rest.foldl (fun (bounds : Int × Int) (x : Int) =>
        (min bounds.1 x, max bounds.2 x)) (first, first)
      some {
        count := Int.ofNat xs.length
        min_ := minMax.1
        max_ := minMax.2
        range := minMax.2 - minMax.1
      }

end Spec

theorem spread_loop1_eq_foldl (rest : List Int) (lo hi : Int) :
    Model.spread_loop1 rest lo hi =
      rest.foldl (fun (bounds : Int × Int) (x : Int) =>
        (min bounds.1 x, max bounds.2 x)) (lo, hi) := by
  induction rest generalizing lo hi with
  | nil =>
      rw [Model.spread_loop1]
      simp only [List.foldl_nil]
  | cons x rest ih =>
      rw [Model.spread_loop1]
      simp only [List.foldl_cons]
      have hlo : (if x < lo then x else lo) = min lo x := by
        by_cases h : x < lo
        · simp [h, min_eq_right (le_of_lt h)]
        · have hle : lo ≤ x := by omega
          simp [h, min_eq_left hle]
      have hhi : (if x > hi then x else hi) = max hi x := by
        by_cases h : x > hi
        · simp [h, max_eq_right (le_of_lt h)]
        · have hle : x ≤ hi := by omega
          simp [h, max_eq_left hle]
      rw [hlo, hhi, ih]

theorem original_meets_spec : ∀ (xs : List (Int)), Model.spread_pre xs = true → Model.spread xs = Spec.spec xs :=
by
  intro xs _
  cases xs with
  | nil => simp [Model.spread, Spec.spec]
  | cons first rest =>
      have hpos : 0 < ((first :: rest).length : Int) := by
        exact_mod_cast (show 0 < (first :: rest).length by simp)
      have hfalse : ¬ (((first :: rest).length : Int) = 0) := by omega
      simp only [Model.spread, hfalse, if_false]
      simp [Faithful.getD, spread_loop1_eq_foldl, Spec.spec, min_self, max_self]

#print axioms original_meets_spec
