import Faithful.Tactics

-- Faithful: spread. Model generated by the fixed translator (docs/TRANSLATOR.md); spec agreed by the user.
-- Agreement hash: sha256:e95580e9811980045688de888939a65b9c00dc92f38e85a8ae61f49d2a9f5325

set_option autoImplicit false
set_option linter.unusedVariables false

namespace Model

structure Rec1 where
  count : Int
  min_ : Int
  max_ : Int
  range : Int
  deriving Repr, Inhabited

instance : Lean.ToJson Rec1 := ⟨fun r => Lean.Json.mkObj [("count", Faithful.jInt r.count), ("min", Faithful.jInt r.min_), ("max", Faithful.jInt r.max_), ("range", Faithful.jInt r.range)]⟩

def spread_loop1 (rest : List (Int)) (lo : Int) (hi : Int) : (Int × Int) :=
  (match rest with
   | [] =>
      (lo, hi)
   | x :: rest_1 =>
      (let lo_2 := (if (x < lo) then
            (let lo_1 := x;
             lo_1)
           else
            lo);
       (let hi_2 := (if (x > hi) then
             (let hi_1 := x;
              hi_1)
            else
             hi);
        (Model.spread_loop1 rest_1 lo_2 hi_2))))
termination_by rest.length
decreasing_by
  faithful_decreasing

def spread (xs : List (Int)) : Option (Model.Rec1) :=
  (if (((xs).length : Int) = (0 : Int)) then
    (none : Option (Model.Rec1))
   else
    (let lo := (Faithful.getD xs (0 : Int));
     (let hi := (Faithful.getD xs (0 : Int));
      (let xs_1 := xs;
       (let (lo_1, hi_1) := (Model.spread_loop1 xs_1 lo hi);
        (some ({ count := ((xs).length : Int), min_ := lo_1, max_ := hi_1, range := (hi_1 - lo_1) } : Model.Rec1)))))))

def spread_loop1_chk (rest : List (Int)) (lo : Int) (hi : Int) : Faithful.Chk ((Int × Int)) :=
  do
    match rest with
    | [] =>
      pure (lo, hi)
    | x :: rest_1 =>
      let lo_2 := (if (x < lo) then
              (let lo_1 := x;
               lo_1)
             else
              lo)
      let hi_2 := (if (x > hi) then
              (let hi_1 := x;
               hi_1)
             else
              hi)
      Model.spread_loop1_chk rest_1 lo_2 hi_2
termination_by rest.length
decreasing_by
  faithful_decreasing

def spread_chk (xs : List (Int)) : Faithful.Chk (Option (Model.Rec1)) :=
  do
    if (((xs).length : Int) = (0 : Int)) then
      pure (none : Option (Model.Rec1))
    else
      Faithful.ck (Faithful.inBounds xs (0 : Int)) "bounds check failed at line 14: xs[0]"
      let lo := (Faithful.getD xs (0 : Int))
      Faithful.ck (Faithful.inBounds xs (0 : Int)) "bounds check failed at line 15: xs[0]"
      let hi := (Faithful.getD xs (0 : Int))
      let xs_1 := xs
      let τ1 ← Model.spread_loop1_chk xs_1 lo hi
      let (lo_1, hi_1) := τ1
      Faithful.ck (Faithful.inRange (hi_1 - lo_1)) "range check failed at line 24: hi - lo"
      pure (some ({ count := ((xs).length : Int), min_ := lo_1, max_ := hi_1, range := (hi_1 - lo_1) } : Model.Rec1))

def spread_rangeOk (xs : List (Int)) : Bool := Faithful.rangeOkOf (Model.spread_chk xs)

def spread_pre (xs : List (Int)) : Bool :=
  (((xs).all (fun e0 => Faithful.intOk e0))) && (Model.spread_rangeOk xs)

end Model

-- agreed spec
namespace Spec

def spec (xs : List Int) : Option (Model.Rec1) :=
  match xs with
  | [] => none
  | x :: rest =>
      let bounds := rest.foldl (fun (acc : Int × Int) value =>
        (min acc.1 value, max acc.2 value)) (x, x)
      some {
        count := Int.ofNat xs.length
        min_ := bounds.1
        max_ := bounds.2
        range := bounds.2 - bounds.1
      }

end Spec

theorem spread_loop_fold (xs : List Int) : ∀ lo hi,
    Model.spread_loop1 xs lo hi =
      xs.foldl (fun (acc : Int × Int) x =>
        (if x < acc.1 then x else acc.1, if x > acc.2 then x else acc.2)) (lo, hi) := by
  intro lo hi
  induction xs generalizing lo hi with
  | nil =>
      rw [Model.spread_loop1]
      rfl
  | cons x rest ih =>
      rw [Model.spread_loop1]
      simp only [List.foldl_cons]
      exact ih _ _

theorem spread_step_minmax (x lo hi : Int) :
    (if x < lo then x else lo, if x > hi then x else hi) = (min lo x, max hi x) := by
  have hmin : (if x < lo then x else lo) = min lo x := by
    by_cases h : x < lo <;> simp [h, min_def] <;> omega
  have hmax : (if x > hi then x else hi) = max hi x := by
    by_cases h : x > hi <;> simp [h, max_def] <;> omega
  exact Prod.ext hmin hmax

theorem spread_fold_minmax (xs : List Int) : ∀ lo hi,
    xs.foldl (fun (acc : Int × Int) x =>
      (if x < acc.1 then x else acc.1, if x > acc.2 then x else acc.2)) (lo, hi) =
    xs.foldl (fun (acc : Int × Int) x => (min acc.1 x, max acc.2 x)) (lo, hi) := by
  intro lo hi
  induction xs generalizing lo hi with
  | nil => rfl
  | cons x rest ih =>
      simp only [List.foldl_cons]
      rw [spread_step_minmax]
      exact ih _ _

theorem original_meets_spec : ∀ (xs : List (Int)), Model.spread_pre xs = true → Model.spread xs = Spec.spec xs :=
by
  intro xs _
  cases xs with
  | nil =>
      simp [Model.spread, Spec.spec]
  | cons x rest =>
      have hzero : ¬ (((x :: rest).length : Int) = 0) := by
        simp only [List.length_cons]
        omega
      have hloop : Model.spread_loop1 (x :: rest) x x =
          rest.foldl (fun (acc : Int × Int) value => (min acc.1 value, max acc.2 value)) (x, x) := by
        rw [spread_loop_fold, spread_fold_minmax]
        simp only [List.foldl_cons]
        simp
      unfold Model.spread
      rw [if_neg hzero]
      simp [Faithful.getD]
      rw [hloop]
      simp [Spec.spec]

#print axioms original_meets_spec
